version: '3'
services:
  app:
    image: my-spring-app
    build:
      context: .
      dockerfile: Dockerfile.spring
    ports:
      - "8111:8111"
  jenkins:
    image: my-ubuntu-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JENKINS_OPTS: --httpPort=8080

  volumes:
    jenkins_home:
